# Generated by Django 4.2.2 on 2023-06-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_entrenador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gimnasio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=20)),
                ('tipo_pokemon', models.CharField(max_length=20)),
            ],
        ),
    ]
