# Generated by Django 4.2.2 on 2023-07-06 00:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_pokemon_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
