# Generated by Django 4.2.2 on 2023-07-08 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_alter_pokemon_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='pokedex',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evolucion',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='iconos'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='tipo',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
