# Generated by Django 4.2.2 on 2023-07-08 22:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
